name: torch
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - annotated-types=0.6.0
  - anyio=4.3.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - exceptiongroup=1.2.0
  - filelock=3.14.0
  - freetype=2.12.1
  - grpcio=1.62.2
  - grpcio-tools=1.62.2
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - hyperframe=6.0.1
  - idna=3.7
  - jinja2=3.1.4
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=17.0.6
  - libdeflate=1.20
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libgrpc=1.62.2
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.24
  - libpng=1.6.43
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsqlite=3.45.3
  - libtiff=4.6.0
  - libwebp-base=1.4.0
  - libxcb=1.15
  - libzlib=1.2.13
  - llvm-openmp=15.0.7
  - markupsafe=2.1.5
  - mpmath=1.3.0
  - ncurses=6.5
  - networkx=3.3
  - numpy=1.26.4
  - openjpeg=2.5.2
  - openssl=3.3.0
  - pillow=10.3.0
  - pip=24.0
  - portalocker=2.8.2
  - protobuf=4.25.3
  - pthread-stubs=0.4
  - pydantic=2.7.1
  - pydantic-core=2.18.2
  - pysocks=1.7.1
  - python=3.12.3
  - python_abi=3.12
  - pytorch=2.3.0
  - pyyaml=6.0.1
  - qdrant-client=1.9.1
  - re2=2023.09.01
  - readline=8.2
  - requests=2.31.0
  - setuptools=69.5.1
  - sniffio=1.3.1
  - sympy=1.12
  - tk=8.6.13
  - torchaudio=2.3.0
  - torchvision=0.18.0
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - urllib3=2.2.1
  - wheel=0.43.0
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xz=5.2.6
  - yaml=0.2.5
  - zstd=1.5.6
  - pip:
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - attrs==23.2.0
      - blinker==1.8.2
      - click==8.1.7
      - datasets==2.19.1
      - dill==0.3.8
      - flask==3.0.3
      - flask-cors==4.0.1
      - frozenlist==1.4.1
      - fsspec==2024.3.1
      - huggingface-hub==0.23.0
      - itsdangerous==2.2.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - packaging==24.0
      - pandas==2.2.2
      - pyarrow==16.1.0
      - pyarrow-hotfix==0.6
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - regex==2024.5.15
      - safetensors==0.4.3
      - six==1.16.0
      - tokenizers==0.19.1
      - tqdm==4.66.4
      - transformers==4.40.2
      - tzdata==2024.1
      - werkzeug==3.0.3
      - xxhash==3.4.1
      - yarl==1.9.4
